# Generated by Django 3.2.3 on 2021-08-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=128)),
                ('photo', models.ImageField(upload_to='')),
                ('islive', models.IntegerField()),
            ],
        ),
    ]
