# Generated by Django 3.2.3 on 2021-08-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('healing', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
                ('detail', models.CharField(max_length=255)),
                ('blog_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
                ('detail', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('testimonial_date', models.DateField()),
            ],
        ),
    ]
