# Generated by Django 3.2.3 on 2021-08-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_blog_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_date',
            field=models.DateField(blank=True),
        ),
    ]
