# Generated by Django 3.2.3 on 2021-08-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_blog_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
