# Generated by Django 3.2.3 on 2021-09-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_auto_20210831_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='healing',
            new_name='heading',
        ),
    ]
