# Generated by Django 3.2.3 on 2021-09-21 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_rename_healing_blog_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='adminpanel.category'),
        ),
    ]
