from django.urls import path

from . import views

urlpatterns = [
     
     # Ajax urls
     path('loaddemo',views.loaddemo,name="load_demo"), 
     path('ajaxloaddemo',views.ajaxloaddemo,name="ajaxloaddemo"),
     path('getdemo',views.getdemo,name="get_demo"),
     path('postdemo',views.postdemo,name="post_demo"),
     path('getmethoddemo',views.getmethoddemo,name="getmethoddemo"),
     path('deletemethoddemo',views.deletemethoddemo,name="deletemethoddemo"),
     path('postmethoddemo',views.postmethoddemo,name="postmethoddemo"),
     path('insertusingajaxdemo',views.insertusingajaxdemo,name="insertusingajaxdemo"),
     path('updateproductusingajax',views.updateproductusingajax,name="updateproductusingajax"),
     path('addtocart',views.addtocart,name="addtocart"),
     
     
     ### forntend Urls
     path('deletefromcart',views.deletefromcart,name='deletefromcart'),
     path('productid',views.productid,name="productid"),
     path('prod/<int:categoryid>',views.frontend_product,name="frontend product"),
     path('frontend_test',views.frontend_test,name="frontend test"),
     path('product_detail/<int:productid>',views.product_detail,name="product_detail"),
     path('cart',views.cart,name="cart"),
     path('checkout',views.checkout,name="checkout"),
     path('login',views.user_login,name="user login"),
     path('register',views.user_register,name="user register"),
     path('user_forgot_password',views.user_forgot_password,name="user forgot password"),
     path('user_change_password',views.user_change_password,name="user change password"),
     path('category',views.frontend_category,name="frontend categories"),
     path('product/<int:categoryid>',views.frontend_product,name="frontend product"),
     path('home/',views.frontend_home,name="frontend home"),
     path('blog_detail/<int:blogid>',views.blog_detail,name="blog detail"),
     path('frontend_testimonial/<int:testimonialid>',views.frontend_testimonial,name="frontend_testimonial"),
     path('user_logout',views.frontend_logout,name="logout"),
          
     ### Admin Urls
     path('', views.index, name='index'),
     path('admin_home/',views.admin_home,name="admin_home"),
     path('', views.parent, name='parent'),
     path('',views.base,name="base"),
     path('test/', views.test, name='test'),
     path('blank/', views.blank, name='blank'),
     path('ifdemo/', views.ifdemo, name='ifdemo'),
     path('ifdemo2/<int:age>',views.ifdemo2,name="ifdemo"),
     path('input/', views.input, name='input'),
     path('simpleinterest_get/', views.simpleinterest_get, name='simpleinterest_get'),
     path('input2/',views.input2,name="input2"),
     path('maths_post/',views.maths_post,name="maths_post"),
     path('bmi/',views.bmi,name="bmi"),
     path('bmiinterest/',views.bmiinterest, name="bmiinterest"),
     path('tri/',views.tri, name="tri"),
     path('triget/',views.triget, name="triget"),
     path('pincodes/',views.pincodes,name="pincodcde"),
     path('insert_pincode/',views.insert_pincode,name="insert_pincode"),
     path('delete_pincode/<int:pincodeid>',views.delete_pincode,name="delete pincode"),
     path('edit_pincode/<int:id>',views.edit_pincode,name="edit pincode"),
     path('schools/',views.schools,name="schools"),
     path('insert_school/',views.insert_school,name="insert_school"),
     path('edit_school/<int:schoolid>',views.edit_school,name="edit_school"),
     path('delete_school/<int:schoolid>',views.delete_school,name="delete school"),
     path('categories/',views.categories,name="categories"),
     path('insert_categories/',views.insert_categories,name="insert_categories"),
     path('edit_categories/<int:id>',views.edit_categories,name="edit categories"),
     path('delete_categories/<int:id>',views.delete_categories,name="delete categories"),
     path('products/',views.products,name="products"),
     path('insert_product/',views.insert_product,name="Insert Products"),
     path('edit_product/<int:id>',views.edit_product,name="Edit Products"),
     path('delete_product/<int:id>',views.delete_product,name="Delete Products"),
     path('logout/',views.logout,name="admin logout"),
     path('forgot_password/',views.forgot_password,name="forgot password"),
     path('change_password/',views.change_password,name="change password"),
     path('signup/',views.signup,name="Signup"),
     path('email',views.email,name="Send Demo Email"),
     path('user/',views.user,name="User"),
     path('insert_user/',views.insert_user,name="Insert User"),
     path('edit_user/<int:id>',views.edit_user,name="Edit User"),
     path('delete_user/<int:id>',views.delete_user,name="Delete User"),
     path('slider/',views.slider,name="slider"),
     path('insert_slider/',views.insert_slider,name="insert_slider"),
     path('edit_slider/<int:id>',views.edit_slider,name="Edit Slider"),
     path('delete_slider/<int:id>',views.delete_slider,name="Delete Slider"),
     path('testimonial/',views.testimonial,name="Testimonial"),
     path('insert_testimonial/',views.insert_testimonial,name="Insert Testimonial"),
     path('edit_testimonial/<int:id>',views.edit_testimonial,name="Edit Testimonial"),
     path('delete_testimonial/<int:id>',views.delete_testimonial,name="Delete Testimonial"),
     path('blog/',views.blog,name="blog"),
     path('insert_blog/',views.insert_blog,name="Insert Blog"),
     path('edit_blog/<int:id>',views.edit_blog,name="Edit Blog"),
     path('delete_blog/<int:id>',views.delete_blog,name="Delete Blog"),
              
] 